services:
  db:
    image: postgres:16.0-bullseye
    restart: always
    container_name: dbpostgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./nodserver/csv/csv-no-id/:/var/lib/postgresql/csv
  
  adminer:
    image: adminer:4.8.1-standalone
    container_name: dbadminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

#  nodapp:
#    build: 
#      context: ./nodserver/dist
#      dockerfile: Dockerfile
#    container_name: nodapp 
#    image: ulimon_img 
#    ports:
#      - '3000:3000'

#    environment:
#      - PG_DB=libro_clases
#      - PG_USER=ulimon
#      - PG_PASSWORD=ul1m0n
#      - PG_HOST=db
#      - NODE_ENV=development
#    volumes:
#      - ./nodserver/dist:/app/dist
      
#    restart: always
#    stdin_open: true
#    tty: true

#    depends_on:
#       - db

#  nginx:
#    build: 
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: nginx-app
#    ports:
#      - 80:80
#    volumes: 
#      - ./nginx/html/nglibro15:/usr/share/nginx/html
#      - ./nginx/letsencrypt:/etc/letsencrypt
      
#volumes:
#  db-data: {}
  
